### ISSUE TITLE
Feedback on the second submission

### ISSUE THREAD

**Issue by Anisha7** [betsybaileyy/CS_3#1]
Good job submitting the second coding challenge. Here's how you can improve:
- ArrayQueue is not implemented. This is required. Reach out if you feel blocked :)
- Missing is subset method in Sets, and failing multiple tests. There are a couple of typos in your tests. You also need to add/subtract from your size property when you add or remove an element from the set. Also remember that hash tables have a method called keys, so it must be called as a function —> map.keys( ). (Its a bug in your union function). Debug your sets against your test functions. :) (Also, in your sets tests, you should not have to access the map property that stores the hash table. You should be able to use set.contains(item), by using your contains method for your sets.

**Comment by Anisha7** [comment]
Sets are good now! However, your queue tests are failing because you are trying to access self.list.size, where self.list is an array. The size property belongs to the class, thus can only be accessed as self.size. You also never increment your size property. Every time you add or remove an element, you should update self.size. Fixing these two issues will allow all of your tests to pass.

**Comment by betsybaileyy** [comment]
array queue now working 👍 . Again, THANK YOU for your feedback!
