### ISSUE TITLE
Feedback on the first submission - regraded

### ISSUE THREAD

**Issue by Anisha7** [betsybaileyy/CS_3#2]
- Search.py: In your recursive binary search function, you never initialize left to a integer. Thus, your function throws an error when you try to do math with ‘left’ because it is None.
- Palindrome iterative does not pass tests. Try to use print statements and the given test cases to see what’s going on.
- I see that you annotated for time complexity. Do the same for space complexity. How much space is your function using? Are you allocating any arrays, sets, dictionaries, etc?

**Comment by betsybaileyy** [comment]
@Anisha7 I have updated my Binary_Search_Recursive in strings which are now passing tests. Similarly, I have done the same for Palindrome Iterative. I struggle to understand the space complexity but have annotated it to the best of my ability. Thank you for your response, it was super helpful and has made my corrections obvious to me 🥇☺️
